### ISSUE TITLE
Won't connect to iPhone 6, but connects to everything else I've tried.

### ISSUE THREAD

**Issue by benguild** [NordicSemiconductor/ble-sdk-arduino#15]
Hi all,
I'm running iOS 8.2 beta 4, and this won't connect to my iPhone 6.

I've gotten the software working with every other device I've tried (2x iPhone 5S, 1 x iPad 3), but at this point I'm not sure where the issue is. It could be an issue with the device, or with the library. It just hangs on pairing with the device ... 
*lib_aci_bond_request(); -> ACI_CMD_BOND_SECURITY_REQUEST -> Device displays prompt, tap "pair" -> nothing (???) -> Eventual timeout and return to advertising mode.*

If it is a bug with the library I was hoping to help debug it and contribute to the project. I've been messing with this for several hours so far but haven't made any progress. Can anyone offer any insight as to where to look for a possible hangup?

**Comment by benguild** [comment]
Did tons of logging, couldn't figure it out. Ended up wiping the device and restoring from a backup. Works fine now, so false alarm and was indeed an issue on the device itself that was pairing.

**Comment by cconway** [comment]
Did you try a restart before the restore? Sometimes iOS will cache the Characteristics and Services. If you were flashing different firmwares with different Services then potentially iOS was out of sync.

**Comment by benguild** [comment]
I tried everything. Wiping the EEPROM on the chipset, restarting the phone, etc. — I really think it's an iOS bug because I could connect to the device but it just wouldn't pair.
